### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by rpbaptist** [lemonwaysas/ruby-client-direckit-json2#1]
When loading the demo app I get the following error:

```ruby
undefined method `[]' for nil:NilClass
```
On line: https://github.com/lemonwaysas/ruby-client-direckit-json2/blob/master/LemonWayApp/app/controllers/scenario_controller.rb#L75

When debugging https://github.com/lemonwaysas/ruby-client-direckit-json2/blob/master/LemonWayApp/app/controllers/scenario_controller.rb#L224

```ruby
[2] pry(#<ScenarioController>)> sendRequest("RegisterCard", "1.2", params)
=> {"d"=>
  {"__type"=>"WonderLib.RegisterCardResult",
   "CARD"=>nil,
   "E"=>
    {"Error"=>"CARD_DATE='12/2016' should be in the future",
     "Code"=>"266",
     "Msg"=>"Bad format for card date",
     "Prio"=>"2",
     "INT_MSG"=>nil}
```

**Comment by pham-dat** [comment]
Thank you.
The to-be-registered card must have a date in the future.

**Comment by rpbaptist** [comment]
I saw that after creating this issue. Thanks for merging my PR

For anyone stumbling across this: https://github.com/lemonwaysas/ruby-client-direckit-json2/pull/2
